name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fix1
      run: sudo apt-get update
    - name: Fix2
      run: sudo apt-get update â€“fix-missing
    - name: Install SDL2
      run: sudo apt-get install libsdl2-dev
    - name: Install SDL2 TTF
      run: sudo apt-get install libsdl2-ttf-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
